apiVersion: v1
kind: ConfigMap
metadata:
  name: hilal-config
data:
  # Database connection split into parts
  DATABASE_TYPE: "POSTGRESQL"
  DATABASE_HOST: "hilal-db-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "auth"

  # App settings
  ENVIRONMENT: "development"
  AUTH_DOMAIN: "localhost:8000"
  AUTH_CLIENT_ID: "12uypqcdxn25pth0d4ekht2svpttiduk"

  # Networking & logging
  FORWARDED_ALLOW_IPS: "*"
  LOG_LEVEL: "INFO"
  PORT: "8000"

  # Concurrency & telemetry
  WEB_CONCURRENCY: "2"
  TELEMETRY_ENABLED: "0"

  # Email (host & username only)
  EMAIL_PROVIDER: "SMTP"
  EMAIL_PROVIDER_HOST: "smtp.gmail.com"
  EMAIL_PROVIDER_PORT: "587"
  EMAIL_PROVIDER_USERNAME: "adnan1470369258@gmail.com"
  EMAIL_PROVIDER: "SMTP"
  EMAIL_PROVIDER_PARAMS: >
    {"host": "smtp.gmail.com",
     "username": "adnan1470369258@gmail.com",
     "password": "ftnjmihphyunhxao"}
