apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hilal-app-hpa
  namespace: default # adjust if you’re using another namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hilal-app
  minReplicas: 1 # never go below 1 pod
  maxReplicas: 5 # cap at 5 pods when under load
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # scale out when avg CPU > 50%
