apiVersion: apps/v1
kind: Deployment
metadata:
  name: hilal-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hilal-redis
  template:
    metadata:
      labels:
        app: hilal-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          # require a password on the server
          command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hilal-secrets
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: hilal-redis-service
spec:
  selector:
    app: hilal-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
