apiVersion: apps/v1
kind: Deployment
metadata:
  name: hilal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hilal-worker
  template:
    metadata:
      labels:
        app: hilal-worker
    spec:
      containers:
        - name: hilal-worker
          image: stagingacr001.azurecr.io/hilal_auth_worker:7ec8e6e
          envFrom:
            - configMapRef:
                name: hilal-config
            - secretRef:
                name: hilal-secrets
